- name: prepare helm YAML files to the first master node
  copy:
    src: "{{ item }}"
    dest: /tmp/
  with_items:
    - helm.sh
    - rbac-config.yaml

- name: prepare helm package manager
  shell: sh /tmp/helm.sh

- name: create service account tiller
  command: kubectl create -f /tmp/rbac-config.yaml

- name: edit clusterrolebind permissive-binding
  command: kubectl create clusterrolebinding permissive-binding --clusterrole=cluster-admin --user=admin --user=kubelet --group=system:serviceaccounts
