- name: init kubeadmin with {{ k8s_runtime_environment }}(single in cmd)
  block:
    - name: init kubeadmin with {{ k8s_runtime_environment }}
      shell: kubeadm init --pod-network-cidr={{ k8s_pod_cidr }} --apiserver-advertise-address={{ ansible_facts[k8s_interface]['ipv4']['address'] }} --cri-socket=/var/run/crio/crio.sock
      register: kube_discovery
    - pause:
        seconds: 10
        prompt: The master nodes successfully installed  
  rescue:
    - name: reset master
      command: kubeadm reset --force
      
    - debug:
        msg: The master nodes has been reseted
      failed_when: ( master_result.rc in [ 1,2 ] )
  when: k8s_instmethod == "cmd"


- name: init kubeadmin with {{ k8s_runtime_environment }}(single in cmd)  
  block:
    - name: init kubeadmin with {{ k8s_runtime_environment }}(single in kubeadm-config)
      shell: kubeadm init --config /tmp/kubeadm-config.yaml
      register: kube_discovery
    - pause:
        seconds: 10
        prompt: The master nodes successfully installed
  rescue:
    - name: reset master
      command: kubeadm reset --force
      
    - debug:
        msg: The master nodes has been reseted
      failed_when: ( master_result.rc in [ 1,2 ] )
  when: k8s_instmethod == "config"