# tasks file for k8s-master
#- import_tasks: containerd.yaml
#  when: k8s_runtime_environment == "containerd"

#- import_tasks: docker.yaml
#  when: k8s_runtime_environment == "docker"

- import_tasks: runtime.yaml

- import_tasks: kubeconfig.yaml
- import_tasks: kubelet.yaml
