---
# tasks file for k18s-master
- name: copy kube-calico file to root home directory
  copy:
   src: kube-calico.yaml
   dest: /tmp/kube-calico.yaml

- name: apply to kube-calico on kubernetes cluster
  shell: KUBECONFIG=/etc/kubernetes/admin.conf kubectl apply -f /tmp/kube-calico.yaml
