- name: init kubeadmin with crio
  block:
    - name: apply sysctl
      command: sysctl --system -q

    - name: init kubeadmin with crio
      shell: kubeadm init --pod-network-cidr="{{ ansible_interfaces | difference(['internal_nic_dev_name'],ansible_default_ipv4.alias]) | first }}" --cri-socket=/var/run/crio/crio.sock
      register: kube_discovery
    - debug:
        msg: The master nodes successfully installed
    - pause:
        seconds: 30
  rescue:
    - name: reset master
      command: kubeadm reset --force
      no_log: yes
    - debug:
        msg: The master nodes has been reseted
      failed_when: master_result.rc in [ 1,2 ]
