- name: copy a master configuration file
  copy:
    src: kubeadm-config.yaml
    dest: /tmp/

- name: init kubeadmin for master node with crio
  shell: kubeadm init --pod-network-cidr={{ subnetnetwork }} --apiserver-advertise-address={{ ansible_facts[internal_nic_dev_name]['ipv4']['address'] }} --cri-socket=/var/run/crio/crio.sock 
  delegate_to: "{{ groups['k8s_master'] | first }}"


- name: copy kubelet config file to /etc/sysconfig
  copy:
    src: files/kubelet
    dest: /etc/sysconfig/kubelet
- pause:
    seconds: 30

- name: get token
  command: kubeadm token create --print-join-command
  register: k8stoken
  delegate_to: "{{ groups['k8s_master'] | first }}"

- name: join the rest of master nodes into first master node cluster
  shell: "{{ k8stoken.stdout }} --control-plane"
  register: master_reg_result
  delegate_to: "{{ groups['k8s_master'] }}"

- pause:
    seconds: 30
    prompt: the rest of master nodes successfully joined to the cluster

- name:
  copy: 
    src: "/etc/kubernetes/{{ item }}"
    dest: /etc/kubernetes/
    mode: 0700
  loop:
    - pki/ca.crt
    - pki/ca.key
    - pki/sa.key
    - pki/sa.pub
    - pki/front-proxy-ca.crt
    - pki/front-proxy-ca.key
    - etcd/ca.crt
    - etcd/ca.key
    - admin.conf
- name:
  shell: |
    kubeadm join --control-plane
