- name: install libvirt daemon service on {{ groups['k8s_node'] }}
  package:
    name: libvirt-daemon
    state: latest

- name: get to the kubevirt CR from github

  get_url:
    url: https://github.com/kubevirt/kubevirt/releases/download/v0.54.0/kubevirt-operator.yaml
    dest: /tmp/kubevirt-operator.yaml

- name: get to the kubevirt CR from github
  get_url:
    url: https://github.com/kubevirt/kubevirt/releases/download/v0.54.0/kubevirt-cr.yaml
    dest: /tmp/kubevirt-cr.yaml

- name: create kubevirt operator and CR
  command: kubectl apply -f "/tmp/{{ item }}"
  loop:
    - kubevirt-operator.yaml
    - kubevirt-cr.yaml

- name: wait for the kubevirt service is available status
  command: kubectl -n kubevirt wait kv kubevirt --for condition=Available
  register: virt_kv    
