- name: register docker repository in yum.repos.d
  yum_repository:
    name: docker-ce
    description: docker CE repository
    baseurl: https://download.docker.com/linux/centos/7/x86_64/stable
    gpgcheck: no
    enabled: yes

- name: check to docker if already install remove from a host
  block:
    - name: install new docker-ce version
      yum:
        name: docker-ce
        state: present
      register: docker_result

    - debug:
        msg: "{{ docker_result }}"
  rescue: 
    - name: remove old docker version
      yum:
        name: "{{ item }}"
        state: absent
      with_items:
        - docker
        - docker-common
      when: docker_result.rc == 0
    - fail:
        msg: docker install and remove are failed

- name: install docker-ce version
  yum:
    name: docker-ce
    state: latest

- name: enabled and started to docker service
  service:
    name: docker
    state: started
    enabled: yes