apiVersion: apps/v1 
kind: Deployment
metadata:
  name: php-apache
spec:
  selector:
    matchLabels:
      app: php-apache
  replicas: 2 
  template:
    metadata:
      labels:
        app: php-apache
    spec:
      containers:
      - name: php
        image: gcr.io/google_containers/hpa-example
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: 100Mi
            cpu: 100m
