---
- name: repository kubernetes for YUM
  copy:
    src: kubernetes.repo
    dest: /etc/yum.repos.d/kubernetes.repo
  when: (ansible_distribution == "CentOS")

- name: import kubernetes GPG key file from kubernetes server
  command: rpmkeys --import https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg