---
# tasks file for k18s-prepare
- include_tasks: firewalld.yaml
- include_tasks: swapoff.yaml
- include_tasks: kernel-mods.yaml
- include_tasks: selinux.yaml
- include_tasks: packages.yaml 

- include_tasks: crio.yaml
  when: runtime_environment == "crio"
- include_tasks: docker.yaml
  when: runtime_environment == "docker"
- include_tasks: kubernetes.yaml


