- name: install tc package for kubernetes
  package:
    name: "{{ item }}"
    state: present
  loop:
    - iproute
    - iproute-tc  

- name: install the kubeadm package for install
  package:
    name: kubeadm
    state: present

- name: install the selinux packages
  package:
    name: "{{ item }}"
  loop:
    - python3-libselinux
    - python3-libsemanage
