- name: label to kubernetes container worker nodes
  shell: kubectl label node {{ nodename }} node-role.kubernetes.io/worker=worker --overwrite
  delegate_to: "{{ groups['k8s_master'][0] }}"
  ignore_errors: yes