- name: set to an IP Address for {{ inventory_hostname }} for eth1
  nmcli:
    type: "{{ item.type }}"
    conn_name: "{{ item.conn_name }}"
    ifname: "{{ item.ifname }}"
    ip4: "{{ item.ip4 }}"
    gw4: "{{ item.gw4 }}"
    state: present
    autoconnect: "{{ item.autocon }}"
  with_items:
    - "{{ nmcli_ethernet }}"

- name: set to an IP address for {{ inventory_hostname }} for eth0
  nmcli:
    type: "{{ k8s_interface_type_ext }}"
    conn_name: "{{ k8s_interface_ext }}"
    ifname: "{{ k8s_interface_ext }}"
    ip4: "{{ (ansible_default_ipv4.network + '/' + ansible_default_ipv4.netmask) | ipaddr('network/prefix') }}"
    gw4: "{{ k8s_ip4_gw_ext }}"
    state: present
    autoconnect: "yes"

- name: deactive and active to the kubernetes internal interface
  block:
    - command: nmcli con mod {{ k8s_interface }} ipv4.method manual
    - command: nmcli con down {{ k8s_interface }}
    - command: nmcli con up {{ k8s_interface }}

- name: add the kubernetes internal interface to firewalld
  firewalld:
    interface: "{{ k8s_interface }}"
    permanent: yes
    state: enabled
    zone: public
  when: use_firewalld

- name: set to a hostname
  hostname:
    name: "{{ nodename }}"
#- name: set to a /etc/hosts file
#  template:
#    src: hosts.j2
#    dest: /etc/hosts