- name: init kubeadmin with crio
  block:
    - name: apply sysctl
      command: sysctl --system -q

    - name: init kubeadmin with crio(single)
      shell: kubeadm init --pod-network-cidr={{ k8s_pod_cidr }} --apiserver-advertise-address={{ ansible_facts[k8s_interface]['ipv4']['address'] }} --cri-socket=/var/run/crio/crio.sock
      register: kube_discovery
      when: k8s_proxy_mode =="single"

    - name: init kubeadmin with crio(multi)
      shell: kubeadm init --pod-network-cidr={{ k8s_pod_cidr }} --apiserver-advertise-address={{ ansible_facts[k8s_interface]['ipv4']['address'] }} --cri-socket=/var/run/crio/crio.sock --control-plane-endpoint={{ groups['lb'] | first }} --upload-certs
      register: kube_discovery
      when: k8s_proxy_mode =="multi"

    - debug:
        msg: The master nodes successfully installed

    - name: get token
      command: kubeadm token create --print-join-command
      register: k8stoken
      delegate_to: "{{ groups['k8s_master'] | first }}"
      run_once: true

  rescue:
    - name: reset master
      command: kubeadm reset --force
      no_log: yes
