- name: start and config to ports for kubernetes
  block:
  - name: start firewalld service
    service:
      name: firewalld
      state: started
      enabled: yes

  - name: enable masquerade to firewalld
    firewalld:
      masquerade: "True"
      zone: public
      state: enabled
      permanent: yes
      
  - name: add ports to firewalld for controller 
    firewalld:
      service: "{{ item }}"
      state: enabled
      permanent: yes
      immediate: yes
      zone: public
    with_items:
      - kube-api
      - kube-apiserver
      - kube-control-plane
      - kube-control-plane-secure
      - kube-controller-manager
      - kube-controller-manager-secure 
      - kube-scheduler
      - kube-scheduler-secure
      - kubelet
      - kubelet-readonly
    when: "{{ groups['k8s_master'] }}"

  - name: add ports to firewalld for worker
    firewalld:
      service: "{{ item }}"
      state: enabled
      permanent: yes
      immediate: yes
      zone: public
    with_items:
      - kube-nodeport-services
      - kube-worker
      - kubelet-worker
    when: "{{ groups['k8s_node'] }}"

  - name: add ports to firewalld for calico
    firewalld:
      port: "{{ item }}"
      state: enabled
      permanent: yes
      immediate: yes
      zone: public
    with_items:      
      - "179/tcp"
      - "4789/udp"
      - "5473/tcp"
      - "51820/udp"
      - "51821/udp"
      - "4789/udp"
      - "443/tcp"
      - "6443/tcp"
      - "6443/tcp"
      - "2379-2380/tcp"
    when: k8s_network =="calico"

  - name: add an rich rule for worker node address to firewalld
    firewalld:
      rich_rule: rule family=ipv4 source address={{ (ansible_default_ipv4.network + '/' + ansible_default_ipv4.netmask) | ansible.utils.ipaddr('network/prefix') }} accept
      permanent: yes
      immediate: yes
      state: enabled
      zone: public
  when: use_firewalld

- name: disabled to the firewalld service permanently
  service:
    name: firewalld
    state: stopped
    enabled: no
  when: not use_firewalld
   
