---
- name: repository kubernetes for YUM
  template:
    src: kubernetes.repo.j2
    dest: /etc/yum.repos.d/kubernetes.repo

- name: copy a containerd repository file
  copy:
    src: containerd.repo
    dest: /etc/yum.repos.d/containerd.repo
  when: k8s_runtime_environment == "containerd"

- name: enable repository for cri-o
  copy:
    src: "{{ item }}"
    dest: /etc/yum.repos.d/
  with_items:
    - devel_kubic_libcontainers_stable_crio.repo
    - devel_kubic_libcontainers_stable.repo
  when: k8s_runtime_environment == "crio"

- name: register docker repository in yum.repos.d
  yum_repository:
    name: docker-ce
    description: docker CE repository
    baseurl: https://download.docker.com/linux/centos/7/x86_64/stable
    gpgcheck: no
    enabled: yes
  when: k8s_runtime_environment == "containerd"    