---
# tasks file for crio
- name: kernel module up to overlay
  command: modprobe "{{ item }}"
  with_items:
    - overlay
    - br_netfilter

- name: enable repository for cri-o
  copy:
    src: "{{ item }}"
    dest: /etc/yum.repos.d/
  with_items:
    - devel:kubic:libcontainers:stable:cri-o:1.18:1.18.3.repo
    - devel:kubic:libcontainers:stable.repo

- name: install to cri-o 
  yum:
    name: cri-o
    state: latest

- name: update to system packages 
  yum:
    name: '*'
    state: latest
    exclude: kernel*
    
- name: net.bridge.bridge-nf-call-iptables, net.ipv4.ip_forward, net.bridge.bridge-nf-call-ip6tables
  lineinfile:
    path: /etc/sysctl.d/99-kubernetes-cri.conf
    state: present
    line: "{{ item }}"
    create: yes
  with_items:
    - "net.bridge.bridge-nf-call-iptables  = 1"
    - "net.ipv4.ip_forward                 = 1"
    - "net.bridge.bridge-nf-call-ip6tables = 1"

- name: enable to sysctl for kubernetes
  command: sysctl --system

- name: disable to swap disk and parition
  command: swapoff -a

- name: enable and start to cri-o .service
  service:
    name: crio
    enabled: yes
    state: started
