- name: generate to ssh key for private and public
  community.crypto.openssh_keypair:
    path: "{{ k8s_private_rsa_locate }}"
    force: True  
  delegate_to: localhost
  
- name: copy the public ssh key file
  authorized_key:
    user: "{{ ansible_user }}"
    key: "{{ lookup('file', '/' + lookup('env', 'USER') + '/.ssh/id_rsa.pub') }}"
  delegate_to: localhost