- name: copy kube-flannel.yml file to root home directory
  copy:
   src: flannel.yaml
   dest: flannel.yaml

- name: apply to kube-flannel on kubernetes cluster
  shell: KUBECONFIG=/etc/kubernetes/admin.conf kubectl apply -f /tmp/flannel.yaml