- name:
  shell: kubeadm init phase upload-certs --upload-certs | tail -1
  register: k8sTls
  delegate_to: "{{ groups['k8s_master'] | first }}"
  run_once: yes

- name: get token
  command: kubeadm token create --print-join-command
  register: k8stoken
  delegate_to: "{{ groups['k8s_master'] | first }}"
  run_once: yes

- name: join the rest of master nodes into first master node cluster
  shell: "{{ k8stoken.stdout }} --control-plane --certificate-key {{ k8sTls.stdout }}"
  register: master_reg_result

- pause:
    seconds: 30
    prompt: the rest of master nodes successfully joined to the cluster

- import_tasks: kubelet.yaml
