- name:
  package:
    name: libvirt-daemon
    state: latest

- name:
  get_url:
    url: https://github.com/kubevirt/kubevirt/releases/download/v0.54.0/kubevirt-operator.yaml
    dest: /tmp/kubevirt-operator.yaml

- name:
  get_url:
    url: https://github.com/kubevirt/kubevirt/releases/download/v0.54.0/kubevirt-cr.yaml
    dest: /tmp/kubevirt-cr.yaml

- name:
  command: kubectl apply -f "/tmp/{{ item }}"
  loop:
    - kubevirt-operator.yaml
    - kubevirt-cr.yaml

- name:
  command: kubectl -n kubevirt wait kv kubevirt --for condition=Available
  register: virt_kv    