- name: install and enable to cri-o,docker enviroment
  hosts: k8s_master:k8s_node
  tags: k8s-prepare
  roles:  
    - { role: core-crio, when: runtime_environment == "crio" }
    - { role: k8s-prepare }

- name: install kubernetes master on the node
  hosts: k8s_master
  tags: k8s-master
  roles:  
    - k8s-master

- name: install kubernetes network service
  hosts: k8s_master
  tags: k8s-network
  roles:  
    - { role: cni-calico, when: k8s_network == "calico" }
    - { role: cni-flanned, when: k8s_network == "flanned" }

- name: install kubernetes nodes
  hosts: k8s_node
  tags: k8s-node
  roles:  
    - k8s-node

- name: install helm on the master node
  hosts: "{{ groups['k8s_master'] | first }}"
  roles:
    - { role: extension-helm/base }
    - { role: extension-helm/metrics, when: enabled_metrics == "enable" }
#   - { role: extension-helm/ingress-haproxy, when: enabled_haproxy == "enable" }
#   - { role: extension-helm/ingress-nginx, when: enabled_nginx == "enable" }

- name: install extension compoments
  hosts: k8s_master
  tags: k8s-extension
  roles:
    - { role: extension-ingress, when: enabled_ingress == "enable" }



