- name: install and enable to cri-o,docker enviroment
  hosts: k8s_master:k8s_node
  tags: k8s-prepare
  roles:  
    - { role: core-crio, when: k8s_runtime_environment == "crio" }
    - { role: k8s-prepare }

- name: install kubernetes master for single node
  hosts: k8s_master 
  tags: k8s-master
  roles:  
    - { role: k8s-master, when: vip_enabled|bool == "yes" }
    - { role: k8s-master-ha, when: k8s_proxy_mode == "multi" }

- name: install kubernetes network service
  hosts: k8s_master
  tags: k8s-network
  roles:  
    - { role: cni-calico, when: k8s_network == "calico" }
    - { role: cni-flanned, when: k8s_network == "flanned" }
    - { role: cni-multus, when: k8s_network == "multus" }
    - { role: cni-kubeovn, when: k8s_network == "kubeovn" }

- name: install kubernetes nodes
  hosts: k8s_node
  tags: k8s-node
  roles:  
    - k8s-node
